"""Build screenplay dictionaries from structured analysis parts."""

from __future__ import annotations

from datetime import datetime, timezone

from .chapter_parser import Chapter
def generate_screenplay_from_parts(
    chapters: list[Chapter],
    chapter_analyses: list[dict],
    story: dict,
    characters: list[dict],
    scenes: list[dict],
    adaptation_note: str = "This output is generated by the configured LLM adapter.",
) -> dict:
    """Generate a screenplay dict following the MVP YAML schema."""
    transitions = [
        {
            "from_scene": scenes[index]["scene_id"],
            "to_scene": scenes[index + 1]["scene_id"],
            "type": "cut",
        }
        for index in range(len(scenes) - 1)
    ]

    return {
        "project": {
            "title": "手稿之夜",
            "source_type": "novel",
            "language": "zh-CN",
            "adaptation_goal": "screenplay_draft",
        },
        "metadata": {
            "author": "",
            "created_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
            "version": "0.1",
            "source_chapter_count": len(chapters),
        },
        "story": story,
        "characters": characters,
        "structure": {
            "acts": [
                {
                    "act_id": "act_1",
                    "title": "发现",
                    "function": "setup",
                    "chapters_covered": [chapters[0].id],
                },
                {
                    "act_id": "act_2",
                    "title": "追查",
                    "function": "confrontation",
                    "chapters_covered": [chapter.id for chapter in chapters[1:-1]],
                },
                {
                    "act_id": "act_3",
                    "title": "抉择",
                    "function": "resolution",
                    "chapters_covered": [chapters[-1].id],
                },
            ]
        },
        "scenes": scenes,
        "transitions": transitions,
        "notes": {
            "adaptation_notes": [adaptation_note],
            "unresolved_issues": [],
        },
    }
